{ config, lib, pkgs, ... }:
let
  cfg = config.doomConfig;
  doomLocalDir = "${config.xdg.configHome}/doom-local";
  caldavPrivateFile = "${doomLocalDir}/caldav.el";
in
{
  options.doomConfig = {
    orgDirectory = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/github.com/scotttrinh/org";
      description = "Directory used by Doom Emacs for Org files.";
    };

    orgRepo = {
      enable = lib.mkEnableOption "activation-time Org repository sync" // {
        default = true;
      };
      url = lib.mkOption {
        type = lib.types.str;
        default = "git@github.com:scotttrinh/org.git";
        description = "Git URL used to clone the Org repository when missing.";
      };
      branch = lib.mkOption {
        type = lib.types.str;
        default = "main";
        description = "Org repository branch to fetch and fast-forward.";
      };
    };

    caldav = {
      enable = lib.mkEnableOption "Doom Emacs CalDAV integration";
      secretKey = lib.mkOption {
        type = lib.types.str;
        default = "EMACS_DOOM_CALDAV_ELISP";
        description = "SOPS key containing private Elisp consumed by Doom CalDAV config.";
      };
    };
  };

  config = {
    xdg.configFile = {
      "doom".source = ../../config/doom/base;

      "doom-local/options.el".text = ''
        ;;; options.el --- generated by Home Manager -*- lexical-binding: t; -*-

        (defvar scott/doom-org-directory ${builtins.toJSON cfg.orgDirectory})
        (defvar scott/doom-caldav-enabled ${if cfg.caldav.enable then "t" else "nil"})
        (defvar scott/doom-caldav-private-file ${builtins.toJSON caldavPrivateFile})
      '';
    };

    sops.secrets = lib.mkIf cfg.caldav.enable {
      doom_caldav_elisp = {
        key = cfg.caldav.secretKey;
        path = caldavPrivateFile;
        mode = "0400";
      };
    };

    home.activation.syncDoomOrgRepo = lib.mkIf cfg.orgRepo.enable (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        org_dir=${lib.escapeShellArg cfg.orgDirectory}
        repo_url=${lib.escapeShellArg cfg.orgRepo.url}
        branch=${lib.escapeShellArg cfg.orgRepo.branch}
        git=${lib.escapeShellArg "${pkgs.git}/bin/git"}

        if [ ! -e "$org_dir" ]; then
          echo "Cloning Org repository to $org_dir..."
          mkdir -p "$(dirname "$org_dir")"
          "$git" clone --branch "$branch" "$repo_url" "$org_dir"
        elif "$git" -C "$org_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
          echo "Fetching Org repository updates in $org_dir..."
          "$git" -C "$org_dir" fetch origin "$branch"
          if [ -z "$("$git" -C "$org_dir" status --porcelain)" ]; then
            "$git" -C "$org_dir" merge --ff-only "origin/$branch" || \
              echo "Warning: Org repository could not fast-forward to origin/$branch."
          else
            echo "Warning: Org repository has local changes; fetched origin only."
          fi
        else
          echo "Warning: $org_dir exists but is not a Git repository; skipping Org sync."
        fi
      ''
    );

    programs.emacs = {
      enable = true;
      extraPackages = epkgs: with epkgs; [
        vterm
        treesit-grammars.with-all-grammars
      ];
    };
  };
}
